### ISSUE TITLE
`"" % + ""` WAT?!?

### ISSUE THREAD

**Issue by LEGOlord208** [Mnpn03/AntiSpam#1]
So, uhh... WTF is `event << "Pruned %d" % num + " messages."`...  
You are basically formatting `"Pruned %d"` with `num` as `%d`. And then concatinating with `" messages."`.

Why?  
The standard ways of doing it are either `"Pruned "  + num.to_s + " messages."` or `"Pruned %d messages." % num`.  
Right now you have a mixture of them both.

**Comment by Mnpn03** [comment]
k

**Comment by Mnpn03** [comment]
I suppose it's on it's way to being resolved - Closed for now. You can at any time open another issue.
